# Generated by Django 4.1.7 on 2023-03-08 18:56

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPlayer',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('fargo', models.IntegerField()),
                ('current_year_earnings', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Pool Tournament', max_length=50)),
                ('director', models.CharField(default='name', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('email', models.EmailField(max_length=50)),
                ('venue', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField(max_length=15)),
                ('date', models.DateField()),
                ('sign_up_time', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('article', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
