# Generated by Django 4.1.7 on 2023-03-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billiard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='article',
        ),
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='news',
            name='article_md',
            field=models.TextField(blank=True, default=None, max_length=4096),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
