# Generated by Django 4.1.7 on 2023-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billiard', '0002_rename_date_listing_start_date_remove_news_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
