# Generated by Django 4.1.7 on 2023-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billiard', '0003_news_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured_image',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
