# Generated by Django 4.1.7 on 2023-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billiard', '0005_alter_listing_zipcode_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
